### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by benman1** [hypebeast/ansible-flaskapp#1]
Hi, 
 I am new to ansible. The ansible-galaxy role was specified incorrectly in the readme. It should be flaskapp, not ansible-flaskapp. The installation command is therefore: 

```
ansible-galaxy install hypebeast.flaskapp
```

**Comment by hypebeast** [comment]
Thanks for reporting the issue. I'll have a look at it.

**Comment by hypebeast** [comment]
You're right. I fixed it.

Thanks for the bug report.
